package:
  name: pyuda
  version: 2.1.1

source:
  git_rev: a75b38edef1
  git_url: ssh://git@git.iter.org/imas/uda.git

requirements:
  host:
    - python
    - setuptools
    - openssl
    - boost
    - swig
    - cmake

  run:
    - python
    - future
    - numpy
    - matplotlib

test:
  imports:
    - pyuda

about:
  home: https://git.iter.org/projects/IMAS/repos/uda/browse
  license: ITER
  license_file: LICENCE.txt
